# Generated by Django 3.2.12 on 2022-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
