# Generated by Django 3.2.12 on 2022-06-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20220608_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('1', '처리중'), ('2', '반려'), ('3', '처리완료')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='suggestion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suggestions.suggestion'),
        ),
    ]
